package com.management.iot.domain;

import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.Date;

/**
 * 自动化配置实体类
 * 对应数据库表：自动化配置表
 * 
 * @author Generated by AI
 * @date 2024
 */
@Data
@TableName(value = "jy_management.iot_automation_config") // 请根据实际表名调整
public class IotAutomationConfig {
    
    /**
     * 自动化配置主键
     */
    private Long automationId;
    
    /**
     * 设备协议ID
     */
    private Long protocolId;
    
    /**
     * 设置温度
     */
    private Double setTemperature;
    
    /**
     * 设置湿度
     */
    private Double setHumidity;
    
    /**
     * 设置光照度
     */
    private Double setIlluminance;
    
    /**
     * 设置土壤湿度
     */
    private Double setSoilMoisture;
    
    /**
     * 设置一氧化碳
     */
    private Double setCarbonMonoxide;
    
    /**
     * 设置二氧化碳
     */
    private Double setCarbonDioxide;
    
    /**
     * 设置紫外线
     */
    private Double setUltravioletRay;
    
    /**
     * 是否启用自动化：0-禁用 1-启用
     */
    private String enabled;
    
    /**
     * 创建时间
     */
    private Date createTime;
    
    /**
     * 修改时间
     */
    private Date updateTime;
}