<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.management</groupId>
        <artifactId>management_system</artifactId>
        <version>3.8.9</version>
    </parent>

    <artifactId>management-business</artifactId>
    <packaging>pom</packaging>
    <description>business业务模块</description>

    <modules>
        <module>management-4GIO</module>
        <module>management-iot</module>
        <module>management-camera</module>
        <module>management-lock</module>
        <module>management-sim</module>
    </modules>

    <dependencies>
        <!-- 通用工具-->
        <dependency>
            <groupId>com.management</groupId>
            <artifactId>management-common</artifactId>
        </dependency>
    </dependencies>

</project>